"""
IoT endpoints — device provisioning and health.

Two endpoints:

  POST /iot/register     unauthenticated (claim code IS the auth)
  POST /iot/heartbeat    HMAC-authenticated

Registration is the only door into the system that doesn't require
existing credentials. It's protected by the claim code.
"""
import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from app.api.deps import require_platform_role  # not used, but pattern ref
from app.core.device_auth import verify_device_signature
from app.db.models.device import Device
from app.db.session import get_db
from app.schemas.iot import (
    DeviceHeartbeatRequest,
    DeviceHeartbeatResponse,
    DeviceRegisterRequest,
    DeviceRegisterResponse,
)
from app.services.iot_service import IoTError, record_heartbeat, register_device


log = logging.getLogger(__name__)

router = APIRouter(prefix="/iot", tags=["iot"])


@router.post(
    "/register",
    response_model=DeviceRegisterResponse,
    status_code=status.HTTP_201_CREATED,
)
def register(
    payload: DeviceRegisterRequest,
    db: Session = Depends(get_db),
):
    """
    Register a new device. Called by the device itself on first boot.

    Authentication = knowledge of a valid claim code. The code is
    generated by a tenant admin, entered into the device's serial
    console, and used exactly once.
    """
    try:
        device = register_device(
            db,
            mac=payload.mac,
            hw_version=payload.hw_version,
            fw_version=payload.fw_version,
            chip=payload.chip,
            claim_code=payload.claim_code,
        )
    except IoTError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return DeviceRegisterResponse(
        device_id=device.id,
        device_serial=device.serial,
        hmac_secret=device.secret_key,
        provisioned_at=device.claimed_at or datetime.now(timezone.utc),
        mqtt=None,
        tls=None,
    )


@router.post(
    "/heartbeat",
    response_model=DeviceHeartbeatResponse,
)
async def heartbeat(
    request: Request,
    db: Session = Depends(get_db),
):
    """
    Device health ping. HMAC-authenticated.

    Headers required:
      X-Device-Serial, X-Timestamp, X-Signature
    (Same recipe as sensor ingest — see app/core/device_auth.py.)
    """
    raw_body = await request.body()

    serial = request.headers.get("X-Device-Serial")
    ts_str = request.headers.get("X-Timestamp")
    signature = request.headers.get("X-Signature")

    if not (serial and ts_str and signature):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing X-Device-Serial, X-Timestamp, or X-Signature",
        )

    # Reuse the existing device signature verifier
    device: Device = verify_device_signature(
        db, serial, ts_str, raw_body, signature
    )

    # Parse body
    try:
        payload = DeviceHeartbeatRequest.model_validate_json(raw_body)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid heartbeat body: {e}",
        )

    record_heartbeat(
        db,
        device,
        uptime_sec=payload.uptime_sec,
        free_heap_kb=payload.free_heap_kb,
        rssi_dbm=payload.rssi_dbm,
        battery_v=payload.battery_v,
        fw_version=payload.fw_version,
    )

    return DeviceHeartbeatResponse(
        status="ok",
        server_time=datetime.now(timezone.utc),
    )