"""
Diagnosis service — calls the vision model to diagnose plant disease.

Architecture:
    Image bytes → base64 → vision model (llama-server, Gemma 3)
    → structured JSON (teacher-mode) → Diagnosis row
    → if requires_chemical: SafetyContext + gate + spray task

Design principles:
- Same abstraction as agent_llm: the model is swappable via config.
- Teacher-mode: the output explains the WHY, not just the WHAT.
- Conservative on chemicals: chemical proposals must pass the safety
  gate AND require human approval.
- Structured output: we validate the JSON before trusting it.
- Fail-safe: model unavailability produces a 'failed' diagnosis.

Note on estimated_cost_lkr:
    The cost estimate is generated by the language model based on
    patterns in its training data. It is NOT a real price — it is
    a plausible-looking guess. Phase 8 (financial ledger) will
    replace this with calculated costs using real tariffs and the
    safety matrix's per-hectare dosing. Until then, treat it as a
    rough ballpark and always surface it with a disclaimer.
"""
import base64
import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from uuid import UUID

from openai import OpenAI
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.safety.context import SafetyContext
from app.core.safety.gate import SafetyViolation, validate_tool_call
from app.core.safety.limits_matrix import get_limits
from app.db.models.diagnosis import Diagnosis
from app.db.models.task import Task
from app.services.context_builder import build_safety_context
from app.services.task_service import create_task_from_agent


log = logging.getLogger(__name__)


# --- Configuration ----------------------------------------------------------

PROMPT_VERSION = "diagnosis_v1"
MODEL_TAG = "gemma-3-4b"
MAX_TOKENS = 800


# --- Client (singleton) -----------------------------------------------------

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(
            base_url=settings.llama_server_url,
            api_key=settings.llama_server_api_key,
        )
    return _client


# --- Output type ------------------------------------------------------------

@dataclass
class DiagnosisResult:
    """Structured output from the vision model."""
    disease: str
    confidence: float
    severity: str
    what_is_happening: str
    treatment_steps: list[str]
    prevention_next_season: list[str]
    estimated_cost_lkr: float
    requires_chemical: bool
    raw_response: str = ""
    model: str = MODEL_TAG
    prompt_version: str = PROMPT_VERSION


# --- System prompt (teacher-mode) -------------------------------------------

SYSTEM_PROMPT = """You are a plant pathologist advising a Sri Lankan farmer.

Your job: analyze a photograph of a crop leaf and provide a TEACHER-MODE diagnosis.

TEACHER-MODE means you explain:

1. WHAT you see (the disease or condition, with confidence)
2. WHY it happens (the biology — what the pathogen is doing, what conditions favor it)
3. WHAT to do this week (concrete treatment steps)
4. HOW to prevent it next season (cultural and management practices)
5. HOW MUCH it will cost to treat (estimate in Sri Lankan Rupees, LKR)

CHARACTER:
- HONEST: if the image is unclear, low confidence, or shows a healthy plant, say so.
- CONSERVATIVE: prefer cultural/mechanical controls over chemicals where possible.
- SPECIFIC: cite symptom details from the image, not generic descriptions.
- LOCAL: reference Sri Lankan conditions (monsoon seasons, common varieties,
  locally available treatments) where relevant.

CHEMICALS:
- Only recommend chemical treatment if the disease clearly warrants it.
- If you recommend a chemical, set "requires_chemical": true.
- Estimate the cost of the full treatment in LKR.

OUTPUT FORMAT:
Respond with a single JSON object. No prose outside the JSON.

{
  "disease": "<name, or 'Healthy' or 'Uncertain'>",
  "confidence": <0.0-1.0>,
  "severity": "<none|low|moderate|high>",
  "what_is_happening": "<2-3 sentences explaining the biology>",
  "treatment_steps": ["<step 1>", "<step 2>", ...],
  "prevention_next_season": ["<practice 1>", "<practice 2>", ...],
  "estimated_cost_lkr": <number>,
  "requires_chemical": <true|false>
}
"""


def _build_user_prompt(plot_crop: str | None, notes: str | None) -> str:
    parts = ["Please diagnose the plant disease visible in this image."]
    if plot_crop:
        parts.append(f"Context: this is a {plot_crop} crop.")
    if notes:
        parts.append(f"Farmer's notes: {notes}")
    parts.append("Respond with JSON only.")
    return " ".join(parts)


# --- Core function ----------------------------------------------------------

def diagnose_image(
    image_bytes: bytes,
    plot_crop: str | None = None,
    notes: str | None = None,
) -> DiagnosisResult:
    """
    Send image to the vision model, get back a structured diagnosis.

    Raises DiagnosisError on unrecoverable failure.
    """
    client = _get_client()

    b64 = base64.b64encode(image_bytes).decode("ascii")

    user_prompt = _build_user_prompt(plot_crop, notes)

    try:
        response = client.chat.completions.create(
            model=settings.vision_model_name,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": user_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
                        },
                    ],
                },
            ],
            max_tokens=MAX_TOKENS,
            temperature=0.2,
        )
    except Exception as e:
        raise DiagnosisError(f"Vision model call failed: {e}") from e

    raw = response.choices[0].message.content or ""
    return _parse_response(raw)


def _parse_response(raw: str) -> DiagnosisResult:
    """Parse the model's JSON output. Raises DiagnosisError on failure."""
    text = raw.strip()
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline > 0:
            text = text[first_newline + 1:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise DiagnosisError(
            f"Model returned non-JSON: {raw[:200]!r}"
        ) from e

    required = {
        "disease", "confidence", "severity",
        "what_is_happening", "treatment_steps",
        "prevention_next_season", "estimated_cost_lkr",
        "requires_chemical",
    }
    missing = required - set(data.keys())
    if missing:
        raise DiagnosisError(f"Model output missing keys: {missing}")

    try:
        confidence = float(data["confidence"])
        if confidence > 1.0:
            confidence = confidence / 100.0
        cost = float(data.get("estimated_cost_lkr") or 0)
        treatment = data.get("treatment_steps") or []
        prevention = data.get("prevention_next_season") or []
        if not isinstance(treatment, list):
            treatment = [str(treatment)]
        if not isinstance(prevention, list):
            prevention = [str(prevention)]

        return DiagnosisResult(
            disease=str(data["disease"])[:200],
            confidence=max(0.0, min(1.0, confidence)),
            severity=str(data["severity"])[:32],
            what_is_happening=str(data["what_is_happening"]),
            treatment_steps=[str(t) for t in treatment],
            prevention_next_season=[str(t) for t in prevention],
            estimated_cost_lkr=cost,
            requires_chemical=bool(data["requires_chemical"]),
            raw_response=raw,
        )
    except (TypeError, ValueError) as e:
        raise DiagnosisError(f"Bad field types in model output: {e}") from e


# --- Exception --------------------------------------------------------------

class DiagnosisError(Exception):
    """Raised when a diagnosis cannot be completed."""
    pass


# --- Task proposal (Phase 7f) -----------------------------------------------

def propose_spray_task_for_diagnosis(
    db: Session,
    diag: Diagnosis,
) -> Task | None:
    """
    When a diagnosis recommends chemical treatment, propose a spray task.

    Safety flow:
        1. Build a SafetyContext for the plot (weather, sensors, crop)
        2. Run validate_tool_call() — the gate applies weather + limits
        3. If the gate passes, create a task with requires_approval=True
        4. Link diag.proposed_task_id to the task

    Returns the created Task, or None if the proposal was suppressed.

    Fail-safe design:
        - Missing plot fields → log warning, skip (diagnosis still valid)
        - Weather suppresses spray → gate writes audit entry, skip
        - Any other failure → log warning, skip

    Rationale for "half the matrix max":
        The vision model doesn't produce reliable per-hectare doses.
        We use half the safety matrix's maximum as a conservative
        starting point. The human approver can adjust before dispatch;
        the gate enforces the ceiling regardless.
    """
    try:
        ctx = build_safety_context(db, diag.plot_id)
    except Exception as e:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"plot context unavailable ({type(e).__name__}: {e})"
        )
        return None

    # Look up the matrix to pick a conservative dose
    limits = get_limits(ctx.crop, ctx.stage, ctx.soil_type, ctx.region)
    if limits is None:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"no safety limits for {ctx.crop}/{ctx.stage.value}/{ctx.soil_type.value}"
        )
        return None

    proposed_dose = round(limits.max_chem_dose_ml_per_ha / 2, 1)
    if proposed_dose <= 0:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"max_chem_dose is 0 for this crop/stage (chemicals not permitted)"
        )
        return None

    args = {"dose_ml_per_ha": proposed_dose}

    # Route through the gate — this is the mandatory safety checkpoint
    try:
        validated = validate_tool_call(
            ctx,
            "spray_chemical",
            args,
            db=db,
            actor="diagnosis_service",
            model=diag.model or MODEL_TAG,
            prompt_version=diag.prompt_version or PROMPT_VERSION,
        )
    except SafetyViolation as e:
        log.info(
            f"Spray proposal for diagnosis {diag.id} suppressed by gate: {e}"
        )
        return None

    # The gate flags spray as requiring approval. Create the task.
    task = create_task_from_agent(
        db,
        ctx,
        decision_tool="spray_chemical",
        decision_args=args,
        decision_reason=(
            f"Diagnosis: {diag.disease} "
            f"(confidence {diag.confidence:.0%}, severity {diag.severity})"
        ),
        requires_approval=True,
        source_audit_id=None,
        device_id=None,
    )

    diag.proposed_task_id = task.id
    db.commit()
    log.info(
        f"Proposed spray task {task.id} for diagnosis {diag.id} "
        f"(dose={proposed_dose} ml/ha)"
    )
    return task


# --- Persistence ------------------------------------------------------------

def run_and_store_diagnosis(
    db: Session,
    diagnosis_id: UUID,
    image_bytes: bytes,
    plot_crop: str | None,
    notes: str | None,
    *,
    auto_propose_spray: bool = True,
) -> Diagnosis:
    """
    Run the vision model and update the Diagnosis row in place.

    If the result requires chemical treatment and auto_propose_spray is
    True (default), also proposes a spray task through the safety gate.
    """
    diag = db.get(Diagnosis, diagnosis_id)
    if diag is None:
        raise DiagnosisError(f"Diagnosis {diagnosis_id} not found")

    try:
        result = diagnose_image(image_bytes, plot_crop, notes)
    except DiagnosisError as e:
        diag.status = "failed"
        diag.error = str(e)
        diag.completed_at = datetime.now(timezone.utc)
        db.commit()
        raise

    diag.status = "complete"
    diag.disease = result.disease
    diag.confidence = result.confidence
    diag.severity = result.severity
    diag.what_is_happening = result.what_is_happening
    diag.treatment_steps = result.treatment_steps
    diag.prevention_next_season = result.prevention_next_season
    diag.estimated_cost_lkr = result.estimated_cost_lkr
    diag.requires_chemical = result.requires_chemical
    diag.model = result.model
    diag.prompt_version = result.prompt_version
    diag.completed_at = datetime.now(timezone.utc)
    db.commit()
    db.refresh(diag)

    # --- Phase 7f: propose a spray task when chemical treatment is needed ---
    if auto_propose_spray and diag.requires_chemical:
        try:
            propose_spray_task_for_diagnosis(db, diag)
        except Exception as e:
            # Never fail the diagnosis because task creation hiccuped.
            log.warning(
                f"Spray proposal failed for diagnosis {diag.id}: "
                f"{type(e).__name__}: {e}"
            )

    return diag