"""
Diagnosis service — calls the vision model to diagnose plant disease.

Architecture:
    Image bytes → base64 → vision model (llama-server, Qwen3-VL)
    → structured JSON (teacher-mode) → Diagnosis row
    → if requires_chemical: SafetyContext + gate + spray task

Design principles:
- Same abstraction as agent_llm: the model is swappable via config.
- Teacher-mode: the output explains the WHY, not just the WHAT.
- Conservative on chemicals: chemical proposals must pass the safety
  gate AND require human approval.
- Structured output: we validate the JSON before trusting it.
- Fail-safe: model unavailability produces a 'failed' diagnosis.
- Multi-shot voting (Phase 9.85d): run the model N times, take the
  majority verdict. ~+5.6 accuracy points for 3x the compute.
- RAG-augmented (Phase 9.85b): retrieve relevant chunks from the
  curated Sri Lankan agricultural knowledge base and inject them into
  the system prompt before each run.

Note on estimated_cost_lkr:
    The cost estimate is generated by the language model based on
    patterns in its training data. It is NOT a real price — it is
    a plausible-looking guess. Phase 8 (financial ledger) will
    replace this with calculated costs using real tariffs and the
    safety matrix's per-hectare dosing. Until then, treat it as a
    rough ballpark and always surface it with a disclaimer.
"""
import base64
import dataclasses
import json
import logging
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from uuid import UUID

from openai import OpenAI
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.safety.context import SafetyContext
from app.core.safety.gate import SafetyViolation, validate_tool_call
from app.core.safety.limits_matrix import get_limits
from app.db.models.diagnosis import Diagnosis
from app.db.models.task import Task
from app.services.context_builder import build_safety_context
from app.services.task_service import create_task_from_agent


log = logging.getLogger(__name__)


# --- Configuration ----------------------------------------------------------

PROMPT_VERSION = "diagnosis_v2_rag"  # bumped: added RAG reference block
MODEL_TAG = "qwen3-vl-8b"
MAX_TOKENS = 800
RAG_TOP_K = 5


# --- Client (singleton) -----------------------------------------------------

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(
            base_url=settings.llama_server_url,
            api_key=settings.llama_server_api_key,
        )
    return _client


# --- Output type ------------------------------------------------------------

@dataclass
class DiagnosisResult:
    """Structured output from the vision model."""
    disease: str
    confidence: float
    severity: str
    what_is_happening: str
    treatment_steps: list[str]
    prevention_next_season: list[str]
    estimated_cost_lkr: float
    requires_chemical: bool
    recommended_ingredient: str | None = None
    recommended_dose_ml_per_ha: float | None = None
    raw_response: str = ""
    model: str = MODEL_TAG
    prompt_version: str = PROMPT_VERSION


# --- System prompt (teacher-mode) -------------------------------------------

SYSTEM_PROMPT = """You are a plant pathologist advising a Sri Lankan farmer.

Your job: analyze a photograph of a crop leaf and provide a TEACHER-MODE diagnosis.

TEACHER-MODE means you explain:

1. WHAT you see (the disease or condition, with confidence)
2. WHY it happens (the biology — what the pathogen is doing, what conditions favor it)
3. WHAT to do this week (concrete treatment steps)
4. HOW to prevent it next season (cultural and management practices)
5. HOW MUCH it will cost to treat (estimate in Sri Lankan Rupees, LKR)

CHARACTER:
- HONEST: if the image is unclear, low confidence, or shows a healthy plant, say so.
- CONSERVATIVE: prefer cultural/mechanical controls over chemicals where possible.
- SPECIFIC: cite symptom details from the image, not generic descriptions.
- LOCAL: reference Sri Lankan conditions (monsoon seasons, common varieties,
  locally available treatments) where relevant.

CHEMICALS:
- Only recommend chemical treatment if the disease clearly warrants it.
- If you recommend a chemical, set "requires_chemical": true and provide
  the structured "recommended_chemical" block below.
- Use the active-ingredient name in snake_case (e.g. "copper_oxychloride",
  "mancozeb", "neem_oil").
- Give a dose in ml of product per hectare (typical range 200-1500).
- Estimate the cost of the full treatment in LKR as a rough ballpark only;
  the platform will calculate the real cost from verified prices.

OUTPUT FORMAT:
Respond with a single JSON object. No prose outside the JSON.

{
  "disease": "<name, or 'Healthy' or 'Uncertain'>",
  "confidence": <0.0-1.0>,
  "severity": "<none|low|moderate|high>",
  "what_is_happening": "<2-3 sentences explaining the biology>",
  "treatment_steps": ["<step 1>", "<step 2>", ...],
  "prevention_next_season": ["<practice 1>", "<practice 2>", ...],
  "estimated_cost_lkr": <number>,
  "requires_chemical": <true|false>,
  "recommended_chemical": {
    "active_ingredient": "<snake_case name>" | null,
    "dose_ml_per_ha": <number> | null
  } | null
}
"""


REFERENCE_INSTRUCTIONS = """REFERENCE MATERIAL (extracts from Sri Lankan agricultural guides,
may be in Sinhala — read the scientific content regardless of language):

{chunks}

END OF REFERENCE MATERIAL.

MANDATORY REASONING PROCESS — follow these steps before writing your JSON:

Step 1. List the visible symptoms in the image (colour, pattern, shape,
        presence of rings, halos, water-soaked edges, wilting, etc.)
        in 2-3 bullet points. Write them out first.

Step 2. Check each visible symptom against the reference material above.
        For each match or mismatch, note the reference number.

Step 3. Compare the top candidate diseases. If two diseases look similar,
        explicitly state what symptom separates them according to the
        reference material (e.g. "concentric rings = Early Blight",
        "water-soaked angular lesions = Bacterial Blight").

Step 4. Only after steps 1-3, choose the diagnosis that the reference
        material supports. If the reference material contradicts your
        first instinct, the reference material wins.

Write steps 1-3 in the "what_is_happening" field of your JSON output,
then write the final diagnosis in the "disease" field.
"""


def _build_user_prompt(plot_crop: str | None, notes: str | None) -> str:
    parts = ["Please diagnose the plant disease visible in this image."]
    if plot_crop:
        parts.append(f"Context: this is a {plot_crop} crop.")
    if notes:
        parts.append(f"Farmer's notes: {notes}")
    parts.append("Respond with JSON only.")
    return " ".join(parts)


# --- RAG retrieval ----------------------------------------------------------

def _retrieve_reference_chunks(
    plot_crop: str | None,
    notes: str | None,
    top_k: int = RAG_TOP_K,
) -> str:
    """
    Retrieve reference material and format it for the prompt.
    Opens its own DB session so callers don't have to pass one in.
    Returns an empty string on any failure — the pipeline proceeds
    without references rather than blocking.
    """
    try:
        from app.db.session import SessionLocal
        from app.services import rag_service

        db = SessionLocal()
        try:
            query = rag_service.build_query(plot_crop, notes)
            hits = rag_service.search(db, query, top_k=top_k)
            if not hits:
                log.info("RAG: no reference chunks retrieved")
                return ""
            log.info(
                f"RAG: retrieved {len(hits)} chunks "
                f"(top match {hits[0].similarity:.2f} from {hits[0].source})"
            )
            return rag_service.format_for_prompt(hits)
        finally:
            db.close()
    except Exception as e:
        log.warning(f"RAG retrieval failed (proceeding without refs): {e}")
        return ""


# --- Core function ----------------------------------------------------------

def diagnose_image(
    image_bytes: bytes,
    plot_crop: str | None = None,
    notes: str | None = None,
    reference_chunks: str = "",
) -> DiagnosisResult:
    """
    Route to cloud (Gemini) or local (Qwen3-VL) based on VISION_PROVIDER.

    - "auto": try cloud first; on any failure, fall back to local.
    - "cloud": cloud only; failure raises.
    - "local": local only.
    """
    provider = (settings.vision_provider or "auto").lower()

    if provider in ("auto", "cloud"):
        try:
            from app.services.cloud_vision_service import diagnose_cloud
            result = diagnose_cloud(image_bytes, plot_crop, notes, reference_chunks)
            log.info(f"[vision] cloud ({result.model}) → {result.disease}")
            return result
        except Exception as e:
            log.warning(f"[vision] cloud failed: {e}")
            if provider == "cloud":
                raise DiagnosisError(f"Cloud vision unavailable: {e}") from e
            log.info("[vision] falling back to local model")

    # Local path (either provider == "local", or auto-fallback)
    result = _diagnose_image_local(image_bytes, plot_crop, notes, reference_chunks)
    log.info(f"[vision] local ({result.model}) → {result.disease}")
    return result


def _diagnose_image_local(
    image_bytes: bytes,
    plot_crop: str | None = None,
    notes: str | None = None,
    reference_chunks: str = "",
) -> DiagnosisResult:
    """Original local llama-server call. Kept as a private function."""
    client = _get_client()

    b64 = base64.b64encode(image_bytes).decode("ascii")

    user_prompt = _build_user_prompt(plot_crop, notes)

    system_prompt = SYSTEM_PROMPT
    if reference_chunks.strip():
        system_prompt = SYSTEM_PROMPT + "\n\n" + REFERENCE_INSTRUCTIONS.format(
            chunks=reference_chunks
        )

    try:
        response = client.chat.completions.create(
            model=settings.vision_model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": user_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{b64}"},
                        },
                    ],
                },
            ],
            max_tokens=MAX_TOKENS,
            temperature=0.2,
        )
    except Exception as e:
        raise DiagnosisError(f"Vision model call failed: {e}") from e

    raw = response.choices[0].message.content or ""
    return _parse_response(raw)


def diagnose_image_multishot(
    image_bytes: bytes,
    plot_crop: str | None = None,
    notes: str | None = None,
    n_runs: int = 3,
) -> DiagnosisResult:
    """
    Run the vision model N times on the same image and vote on the verdict.

    Retrieval happens ONCE (it doesn't depend on the image), then the
    same reference block is used for all N runs. Majority disease wins;
    confidence is averaged across agreeing runs.
    """
    if n_runs < 1:
        raise DiagnosisError("n_runs must be >= 1")

    # --- Retrieve reference material once ---
    reference_chunks = _retrieve_reference_chunks(plot_crop, notes)

    results: list[DiagnosisResult] = []
    last_error: Exception | None = None

    for i in range(n_runs):
        try:
            r = diagnose_image(
                image_bytes, plot_crop, notes, reference_chunks=reference_chunks
            )
            results.append(r)
        except DiagnosisError as e:
            last_error = e
            log.warning(f"Multi-shot run {i+1}/{n_runs} failed: {e}")

    if not results:
        raise DiagnosisError(
            f"All {n_runs} multi-shot runs failed. "
            f"Last error: {last_error}"
        )

    # Majority vote on the disease name
    counts = Counter(r.disease for r in results)
    majority_disease, agree_count = counts.most_common(1)[0]

    # Pick a representative result from the majority
    majority_result = next(
        r for r in results if r.disease == majority_disease
    )

    # Average confidence across the agreeing runs
    agreeing = [r for r in results if r.disease == majority_disease]
    avg_confidence = sum(r.confidence for r in agreeing) / len(agreeing)

    log.info(
        f"Multi-shot verdict: {majority_disease!r} "
        f"({agree_count}/{len(results)} runs agreed, "
        f"avg confidence {avg_confidence:.2f})"
    )

    # Build a combined raw response for audit
    combined_raw = "=== MULTI-SHOT VOTING ===\n"
    if reference_chunks:
        # Truncate reference block for the audit log to keep it readable
        combined_raw += f"\n--- RAG reference ({len(reference_chunks)} chars) ---\n"
    for i, r in enumerate(results, 1):
        combined_raw += (
            f"\n--- Run {i} ---\n"
            f"Verdict: {r.disease}  |  Confidence: {r.confidence:.2f}  "
            f"|  Severity: {r.severity}\n"
            f"{r.raw_response}\n"
        )

    return dataclasses.replace(
        majority_result,
        confidence=avg_confidence,
        raw_response=combined_raw,
    )


def _parse_response(raw: str) -> DiagnosisResult:
    """Parse the model's JSON output. Raises DiagnosisError on failure."""
    text = raw.strip()
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline > 0:
            text = text[first_newline + 1:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise DiagnosisError(
            f"Model returned non-JSON: {raw[:200]!r}"
        ) from e

    required = {
        "disease", "confidence", "severity",
        "what_is_happening", "treatment_steps",
        "prevention_next_season", "estimated_cost_lkr",
        "requires_chemical",
    }
    missing = required - set(data.keys())
    if missing:
        raise DiagnosisError(f"Model output missing keys: {missing}")

    try:
        confidence = float(data["confidence"])
        if confidence > 1.0:
            confidence = confidence / 100.0
        cost = float(data.get("estimated_cost_lkr") or 0)
        treatment = data.get("treatment_steps") or []
        prevention = data.get("prevention_next_season") or []
        if not isinstance(treatment, list):
            treatment = [str(treatment)]
        if not isinstance(prevention, list):
            prevention = [str(prevention)]

        # Parse the structured chemical block if present
        ingredient: str | None = None
        dose: float | None = None
        chem_block = data.get("recommended_chemical")
        if isinstance(chem_block, dict):
            ing = chem_block.get("active_ingredient")
            if isinstance(ing, str) and ing.strip():
                ingredient = ing.strip().lower().replace(" ", "_")
            d = chem_block.get("dose_ml_per_ha")
            if isinstance(d, (int, float)) and d > 0:
                dose = float(d)

        return DiagnosisResult(
            disease=str(data["disease"])[:200],
            confidence=max(0.0, min(1.0, confidence)),
            severity=str(data["severity"])[:32],
            what_is_happening=str(data["what_is_happening"]),
            treatment_steps=[str(t) for t in treatment],
            prevention_next_season=[str(t) for t in prevention],
            estimated_cost_lkr=cost,
            requires_chemical=bool(data["requires_chemical"]),
            recommended_ingredient=ingredient,
            recommended_dose_ml_per_ha=dose,
            raw_response=raw,
        )
    except (TypeError, ValueError) as e:
        raise DiagnosisError(f"Bad field types in model output: {e}") from e


# --- Exception --------------------------------------------------------------

class DiagnosisError(Exception):
    """Raised when a diagnosis cannot be completed."""
    pass


# --- Cost calculation (Phase 8d) --------------------------------------------

def calculate_diagnosis_cost(
    db: Session,
    diag: "Diagnosis",
) -> tuple[float | None, dict | None]:
    """
    Calculate the real cost of the recommended treatment from input_prices.

    Returns (calculated_cost_lkr, breakdown_dict).
    Returns (None, None) if we can't calculate (no chemical, no price, etc.).

    Uses the same assumptions as ledger_service for chemical + water + labor.
    """
    from decimal import Decimal

    from app.db.models.input_price import InputCategory
    from app.db.models.plot import Plot
    from app.services import agricultural_constants as const
    from app.services.pricing_service import get_price

    if not diag.recommended_ingredient or not diag.recommended_dose_ml_per_ha:
        return None, None

    plot = db.get(Plot, diag.plot_id)
    if plot is None:
        return None, None

    area_ha = Decimal(str(plot.area_ha or 0))
    if area_ha <= 0:
        area_ha = Decimal("0.1")   # smallholder fallback

    dose = Decimal(str(diag.recommended_dose_ml_per_ha))

    # Look up the chemical price
    chem_price = get_price(
        db,
        active_ingredient=diag.recommended_ingredient,
        tenant_id=diag.tenant_id,
    )
    if chem_price is None:
        return None, {"error": f"no price for {diag.recommended_ingredient}"}

    # Look up water and labor prices
    water_price = get_price(db, active_ingredient="water", tenant_id=diag.tenant_id)
    labor_price = get_price(db, active_ingredient="farm_labor_general", tenant_id=diag.tenant_id)

    # Calculate each line item
    breakdown: dict = {"lines": []}
    total = Decimal("0")

    # Chemical
    chem_kg = (dose * area_ha) / Decimal("1000")
    chem_unit_price = Decimal(str(chem_price.price_lkr))
    chem_amount = (chem_kg * chem_unit_price).quantize(Decimal("0.01"))
    total += chem_amount
    breakdown["lines"].append({
        "category": "chemical",
        "product": chem_price.product_name,
        "qty": float(chem_kg),
        "unit": chem_price.unit,
        "unit_price_lkr": float(chem_unit_price),
        "amount_lkr": float(chem_amount),
    })

    # Water (carrier)
    if water_price is not None:
        carrier_L = const.DEFAULT_SPRAY_CARRIER_L_PER_HA * area_ha
        water_unit_price = Decimal(str(water_price.price_lkr))
        water_amount = (carrier_L * water_unit_price).quantize(Decimal("0.01"))
        total += water_amount
        breakdown["lines"].append({
            "category": "water",
            "product": water_price.product_name,
            "qty": float(carrier_L),
            "unit": "L",
            "unit_price_lkr": float(water_unit_price),
            "amount_lkr": float(water_amount),
        })

    # Labor
    if labor_price is not None:
        labor_hr = const.DEFAULT_SPRAY_LABOR_HOURS_PER_HA * area_ha
        labor_unit_price = Decimal(str(labor_price.price_lkr))
        labor_amount = (labor_hr * labor_unit_price).quantize(Decimal("0.01"))
        total += labor_amount
        breakdown["lines"].append({
            "category": "labor",
            "product": labor_price.product_name,
            "qty": float(labor_hr),
            "unit": "hr",
            "unit_price_lkr": float(labor_unit_price),
            "amount_lkr": float(labor_amount),
        })

    breakdown["total_lkr"] = float(total)
    breakdown["area_ha"] = float(area_ha)
    breakdown["dose_ml_per_ha"] = float(dose)

    return float(total), breakdown


# --- Task proposal (Phase 7f) -----------------------------------------------

def propose_spray_task_for_diagnosis(
    db: Session,
    diag: Diagnosis,
) -> Task | None:
    """
    When a diagnosis recommends chemical treatment, propose a spray task.

    Safety flow:
        1. Build a SafetyContext for the plot (weather, sensors, crop)
        2. Run validate_tool_call() — the gate applies weather + limits
        3. If the gate passes, create a task with requires_approval=True
        4. Link diag.proposed_task_id to the task

    Returns the created Task, or None if the proposal was suppressed.
    """
    try:
        ctx = build_safety_context(db, diag.plot_id)
    except Exception as e:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"plot context unavailable ({type(e).__name__}: {e})"
        )
        return None

    # Look up the matrix to pick a conservative dose
    limits = get_limits(ctx.crop, ctx.stage, ctx.soil_type, ctx.region)
    if limits is None:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"no safety limits for {ctx.crop}/{ctx.stage.value}/{ctx.soil_type.value}"
        )
        return None

    proposed_dose = round(limits.max_chem_dose_ml_per_ha / 2, 1)
    if proposed_dose <= 0:
        log.info(
            f"Cannot propose spray task for diagnosis {diag.id}: "
            f"max_chem_dose is 0 for this crop/stage (chemicals not permitted)"
        )
        return None

    args = {"dose_ml_per_ha": proposed_dose}

    # Route through the gate — this is the mandatory safety checkpoint
    try:
        validated = validate_tool_call(
            ctx,
            "spray_chemical",
            args,
            db=db,
            actor="diagnosis_service",
            model=diag.model or MODEL_TAG,
            prompt_version=diag.prompt_version or PROMPT_VERSION,
        )
    except SafetyViolation as e:
        log.info(
            f"Spray proposal for diagnosis {diag.id} suppressed by gate: {e}"
        )
        return None

    # The gate flags spray as requiring approval. Create the task.
    task = create_task_from_agent(
        db,
        ctx,
        decision_tool="spray_chemical",
        decision_args=args,
        decision_reason=(
            f"Diagnosis: {diag.disease} "
            f"(confidence {diag.confidence:.0%}, severity {diag.severity})"
        ),
        requires_approval=True,
        source_audit_id=None,
        device_id=None,
    )

    diag.proposed_task_id = task.id
    db.commit()
    log.info(
        f"Proposed spray task {task.id} for diagnosis {diag.id} "
        f"(dose={proposed_dose} ml/ha)"
    )
    return task


# --- Persistence ------------------------------------------------------------

def run_and_store_diagnosis(
    db: Session,
    diagnosis_id: UUID,
    image_bytes: bytes,
    plot_crop: str | None,
    notes: str | None,
    *,
    auto_propose_spray: bool = True,
) -> Diagnosis:
    """
    Run the vision model and update the Diagnosis row in place.

    If the result requires chemical treatment and auto_propose_spray is
    True (default), also proposes a spray task through the safety gate.
    """
    diag = db.get(Diagnosis, diagnosis_id)
    if diag is None:
        raise DiagnosisError(f"Diagnosis {diagnosis_id} not found")

    try:
        # Phase 9.85d — multi-shot voting (3 runs, majority verdict)
        # Phase 9.85b — RAG: reference chunks retrieved inside
        result = diagnose_image_multishot(image_bytes, plot_crop, notes, n_runs=3)
    except DiagnosisError as e:
        diag.status = "failed"
        diag.error = str(e)
        diag.completed_at = datetime.now(timezone.utc)
        db.commit()
        raise

    diag.status = "complete"
    diag.disease = result.disease
    diag.confidence = result.confidence
    diag.severity = result.severity
    diag.what_is_happening = result.what_is_happening
    diag.treatment_steps = result.treatment_steps
    diag.prevention_next_season = result.prevention_next_season
    diag.estimated_cost_lkr = result.estimated_cost_lkr
    diag.requires_chemical = result.requires_chemical
    diag.recommended_ingredient = result.recommended_ingredient
    diag.recommended_dose_ml_per_ha = result.recommended_dose_ml_per_ha
    diag.model = result.model
    diag.prompt_version = result.prompt_version
    diag.completed_at = datetime.now(timezone.utc)

    # Phase 8d — calculate the real cost from input_prices (best-effort)
    try:
        calculated, basis = calculate_diagnosis_cost(db, diag)
        if calculated is not None:
            diag.calculated_cost_lkr = calculated
            diag.calculation_basis = basis
    except Exception as e:
        log.warning(f"Cost calculation failed for diagnosis {diag.id}: {e}")

    db.commit()
    db.refresh(diag)

    # --- Phase 7f: propose a spray task when chemical treatment is needed ---
    if auto_propose_spray and diag.requires_chemical:
        try:
            propose_spray_task_for_diagnosis(db, diag)
        except Exception as e:
            # Never fail the diagnosis because task creation hiccuped.
            log.warning(
                f"Spray proposal failed for diagnosis {diag.id}: "
                f"{type(e).__name__}: {e}"
            )

    return diag