"""add diagnoses table

Revision ID: 1f83602b1129
Revises: 8efd43512baa
Create Date: 2026-10-04 11:06:53.530022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f83602b1129'
down_revision: Union[str, None] = '8efd43512baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('image_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('disease', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('what_is_happening', sa.Text(), nullable=True),
    sa.Column('treatment_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prevention_next_season', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost_lkr', sa.Float(), nullable=True),
    sa.Column('requires_chemical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('proposed_task_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_image_hash'), 'diagnoses', ['image_hash'], unique=False)
    op.create_index(op.f('ix_diagnoses_plot_id'), 'diagnoses', ['plot_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_status'), 'diagnoses', ['status'], unique=False)
    op.create_index(op.f('ix_diagnoses_tenant_id'), 'diagnoses', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_tenant_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_status'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_plot_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_image_hash'), table_name='diagnoses')
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
