"""add financial ledger table

Revision ID: 2a3ccf89fb0b
Revises: f5f0ea640775
Create Date: 2026-10-04 13:37:48.309560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3ccf89fb0b'
down_revision: Union[str, None] = 'f5f0ea640775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('WATER', 'FERTILIZER', 'CHEMICAL', 'LABOR', 'ENERGY', 'FUEL', 'SEED', 'EQUIPMENT', 'OTHER', name='ledger_category'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price_lkr', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount_lkr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('input_price_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['crop_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['input_price_id'], ['input_prices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_ledger_batch_id'), 'financial_ledger', ['batch_id'], unique=False)
    op.create_index(op.f('ix_financial_ledger_category'), 'financial_ledger', ['category'], unique=False)
    op.create_index(op.f('ix_financial_ledger_occurred_at'), 'financial_ledger', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_financial_ledger_plot_id'), 'financial_ledger', ['plot_id'], unique=False)
    op.create_index(op.f('ix_financial_ledger_source_task_id'), 'financial_ledger', ['source_task_id'], unique=False)
    op.create_index(op.f('ix_financial_ledger_tenant_id'), 'financial_ledger', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_ledger_tenant_id'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_source_task_id'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_plot_id'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_occurred_at'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_category'), table_name='financial_ledger')
    op.drop_index(op.f('ix_financial_ledger_batch_id'), table_name='financial_ledger')
    op.drop_table('financial_ledger')
    # ### end Alembic commands ###
