"""add calculated cost and structured chemical to diagnoses

Revision ID: 69f222193d1b
Revises: 2a3ccf89fb0b
Create Date: 2026-10-04 14:11:32.585077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f222193d1b'
down_revision: Union[str, None] = '2a3ccf89fb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('recommended_ingredient', sa.String(length=120), nullable=True))
    op.add_column('diagnoses', sa.Column('recommended_dose_ml_per_ha', sa.Float(), nullable=True))
    op.add_column('diagnoses', sa.Column('calculated_cost_lkr', sa.Float(), nullable=True))
    op.add_column('diagnoses', sa.Column('cost_calculation_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'cost_calculation_basis')
    op.drop_column('diagnoses', 'calculated_cost_lkr')
    op.drop_column('diagnoses', 'recommended_dose_ml_per_ha')
    op.drop_column('diagnoses', 'recommended_ingredient')
    # ### end Alembic commands ###
