"""add users table with dual-role design

Revision ID: b9e77a0d59c4
Revises: f43e51beccc1
Create Date: 2026-09-29 22:43:22.828967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e77a0d59c4'
down_revision: Union[str, None] = 'f43e51beccc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('tenant_role', sa.Enum('VIEWER', 'OPERATOR', 'AGRONOMIST', 'TENANT_ADMIN', name='tenant_role'), nullable=True),
    sa.Column('platform_role', sa.Enum('SUPPORT_AGENT', 'PLATFORM_ADMIN', 'SUPER_ADMIN', name='platform_role'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(  tenant_id IS NOT NULL AND tenant_role IS NOT NULL AND platform_role IS NULL) OR (  tenant_id IS NULL AND tenant_role IS NULL AND platform_role IS NOT NULL)', name='ck_users_role_consistency'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
