"""add crop batches and sensor readings hypertable

Revision ID: be67137769d3
Revises: b9e77a0d59c4
Create Date: 2026-10-02 14:16:23.619654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67137769d3'
down_revision: Union[str, None] = 'b9e77a0d59c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('crop', sa.String(length=64), nullable=False),
    sa.Column('variety', sa.String(length=64), nullable=True),
    sa.Column('planted_at', sa.Date(), nullable=False),
    sa.Column('expected_harvest_at', sa.Date(), nullable=True),
    sa.Column('harvested_at', sa.Date(), nullable=True),
    sa.Column('expected_yield_kg', sa.Float(), nullable=True),
    sa.Column('actual_yield_kg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_batches_plot_id'), 'crop_batches', ['plot_id'], unique=False)
    op.create_index(op.f('ix_crop_batches_tenant_id'), 'crop_batches', ['tenant_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'device_id', 'metric')
    )
    op.create_index(op.f('ix_sensor_readings_tenant_id'), 'sensor_readings', ['tenant_id'], unique=False)

    # Convert the regular table into a TimescaleDB hypertable partitioned by `time`.
    # Must run AFTER create_table — Timescale converts existing tables.
    op.execute("SELECT create_hypertable('sensor_readings', 'time', if_not_exists => TRUE);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_tenant_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_crop_batches_tenant_id'), table_name='crop_batches')
    op.drop_index(op.f('ix_crop_batches_plot_id'), table_name='crop_batches')
    op.drop_table('crop_batches')
    # ### end Alembic commands ###