"""add field_events table

Revision ID: d6c7e313333a
Revises: 69f222193d1b
Create Date: 2026-10-04 14:23:23.675406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6c7e313333a'
down_revision: Union[str, None] = '69f222193d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('OVERRIDE', 'OUTCOME', 'OBSERVATION', name='field_event_type'), nullable=False),
    sa.Column('action_taken', sa.String(length=64), nullable=True),
    sa.Column('related_audit_id', sa.BigInteger(), nullable=True),
    sa.Column('related_task_id', sa.UUID(), nullable=True),
    sa.Column('related_diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('reported_by', sa.String(length=128), nullable=False),
    sa.Column('weather_forecast_mm', sa.Float(), nullable=True),
    sa.Column('weather_actual_mm', sa.Float(), nullable=True),
    sa.Column('forecast_window_hours', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('WORKED', 'FAILED', 'UNKNOWN', name='field_event_outcome'), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_audit_id'], ['audit_log.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_events_event_type'), 'field_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_field_events_occurred_at'), 'field_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_field_events_plot_id'), 'field_events', ['plot_id'], unique=False)
    op.create_index(op.f('ix_field_events_tenant_id'), 'field_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_events_tenant_id'), table_name='field_events')
    op.drop_index(op.f('ix_field_events_plot_id'), table_name='field_events')
    op.drop_index(op.f('ix_field_events_occurred_at'), table_name='field_events')
    op.drop_index(op.f('ix_field_events_event_type'), table_name='field_events')
    op.drop_table('field_events')
    # ### end Alembic commands ###
