"""add device secret key for HMAC auth

Revision ID: e1b6b5a7733a
Revises: be67137769d3
Create Date: 2026-10-02 14:31:15.507788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b6b5a7733a'
down_revision: Union[str, None] = 'be67137769d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('secret_key', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_devices_secret_key'), 'devices', ['secret_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: sensor_readings_time_idx is managed by TimescaleDB, not by us.
    # We do NOT recreate or drop it here — see alembic/env.py include_object.
    op.drop_index(op.f('ix_devices_secret_key'), table_name='devices')
    op.drop_column('devices', 'secret_key')
    # ### end Alembic commands ###