"""add input prices table

Revision ID: f5f0ea640775
Revises: 1f83602b1129
Create Date: 2026-10-04 13:31:42.715141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f0ea640775'
down_revision: Union[str, None] = '1f83602b1129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('FUNGICIDE', 'INSECTICIDE', 'HERBICIDE', 'FERTILIZER', 'WATER', 'LABOR', 'ENERGY', 'FUEL', 'SEED', 'OTHER', name='input_category'), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('active_ingredient', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_lkr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('region', sa.String(length=16), server_default='LK', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_prices_active_ingredient'), 'input_prices', ['active_ingredient'], unique=False)
    op.create_index(op.f('ix_input_prices_category'), 'input_prices', ['category'], unique=False)
    op.create_index(op.f('ix_input_prices_product_name'), 'input_prices', ['product_name'], unique=False)
    op.create_index(op.f('ix_input_prices_tenant_id'), 'input_prices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_input_prices_tenant_id'), table_name='input_prices')
    op.drop_index(op.f('ix_input_prices_product_name'), table_name='input_prices')
    op.drop_index(op.f('ix_input_prices_category'), table_name='input_prices')
    op.drop_index(op.f('ix_input_prices_active_ingredient'), table_name='input_prices')
    op.drop_table('input_prices')
    # ### end Alembic commands ###
