"""add soil_type to plots

Revision ID: f75a4098a4ac
Revises: 55c8231ee76b
Create Date: 2026-10-03 09:19:34.860509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75a4098a4ac'
down_revision: Union[str, None] = '55c8231ee76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plots', sa.Column('soil_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plots', 'soil_type')
    # ### end Alembic commands ###
